services:

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: retail_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pipeline:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: retail_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

volumes:
  postgres_data: